---
title: "Ammissione Laurea Triennale (SSE)"
lang: it
page-layout: full
---

Il corso di laurea in Scienze statistiche ed economiche è a **numero programmato** e per l’ammissione al corso di laurea è necessario sostenere il TOLC-E (Test On Line CISIA – Economia) in una delle sedi accreditate. Lo studente potrà sostenere il test in due modalità di erogazione differenti:

  - online presso le sedi universitarie aderenti a CISIA (TOLC)

  - online dal proprio domicilio (TOLC@CASA).

Le informazioni per l’accesso al test, l’elenco delle sedi e le date in cui è possibile sostenerlo, sono disponibili sul sito del CISIA (Consorzio Interuniversitario Sistemi Integrati per l’Accesso [](www.cisiaonline.it/area-tematica-tolceconomia/home-tolc-economia).

 
Tutte le informazioni relative allo svolgimento del Test (TOLC-E), la graduatoria e le immatricolazioni  sono consultabili sul sito web dell’Università degli Studi di Milano – Bicocca nella [pagina del Corso di laurea](https://www.unimib.it/triennale/scienze-statistiche-economiche).

[Clicca qui](https://www.unimib.it/node/25408) per consultare il Bando di concorso (doppia selezione) per l'A.A. 2024-2025 e per informarti sulla procedura di registrazione e iscrizione su segreterie on line.

- Per ulteriori informazioni sulle ammissioni, sul bando e sulle immatricolazioni, contattare l’Ufficio Segreteria studenti: segr.studenti.ecostat@unimib.it

#### Nota

Si segnala che per l’ammissione al 2° o 3° anno del Corso di laurea in Scienze statistiche ed economiche, gli studenti aventi una carriera pregressa, provenienti da altri Corsi di studio di questo o altro ateneo e gli studenti rinunciatari (ossia precedentemente iscritti a dei Corsi di studio), una volta letto il bando con attenzione, potranno richiedere la valutazione della carriera pregressa soltanto quando avranno risposto al bando stesso, candidandosi al 2° o 3° anno,  attenendosi alle disposizioni in esso contenute.