---
title: "Scienze Statistiche ed Economiche"
subtitle: "Università degli studi di Milano-Bicocca"
page-layout: full
toc: false
lang: it   
listing:
  id: news
  type: default
  fields: [date, title, author, description]
  contents: news
  image-placeholder: img/logo2.jpg
  sort:
    - "date desc"
  max-items: 4
---


## Benvenuto {.central}

La Statistica è una scienza relativamente giovane, nata tre secoli fa e sviluppatasi rapidamente negli ultimi cento anni. Pur non essendo molto insegnata nelle scuole superiori, la statistica pervade tutte le altre discipline: viene usata in medicina, in economia, in sociologia, nel marketing, nella finanza, nelle scienze sperimentali, ecc. Questo fa dello statistico una figura molto ricercata e apprezzata nel mercato del lavoro.

Per studiare statistica è certamente utile una certa predisposizione per la matematica, ma è ancora più necessaria la curiosità per il mondo che ci circonda. Infatti la statistica fornisce metodi per osservare il mondo e per trasformare tali osservazioni in informazioni e in decisioni.

## [Avvisi e News](news.qmd) {.central}


::: {#news}
:::

